#!/usr/bin/env bash

export HERE="$(dirname "$(readlink -f "${0}")")"

appimage=$(readlink -f "${1}")

appimage_data=$("${HERE}/appimage-inspector" "${appimage}" 2> /dev/null)

[ ! "${?}" = "0" ] && {
  echo "${appimage_data}"
  exit 1
}

desktop=$(echo "${appimage_data}" | sed -n 1p)
icon=$(echo "${appimage_data}"    | sed -n 2p)
offset=$(echo "${appimage_data}"  | sed -n 3p)

[ -z "${desktop}" ] && {
  echo "Error: AppImage '${1}' is not to be installed"
  exit 1
}

[ -z "${icon}" ] && {
  cp "${HERE}/AppImage.png" "${working_dir}/squashfs-root/icn.png" &> /dev/null
  icon="icn.png"
  exit 1
}

working_dir=$(mktemp -d)
cd "${working_dir}"

unsquashfs -f -o "${offset}" "${appimage}" "${icon}"         -d "${working_dir}" &> /dev/null
unsquashfs -f -o "${offset}" "${appimage}" "${desktop}"      -d "${working_dir}" &> /dev/null
unsquashfs -f -o "${offset}" "${appimage}" "usr/share/mime/" -d "${working_dir}" &> /dev/null

rsvg-convert "${working_dir}/squashfs-root/${icon}"                                      &> /dev/null
convert -resize 128x128 "${working_dir}/squashfs-root/${icon}" "${working_dir}/icon.png" &> /dev/null

mv "${working_dir}/squashfs-root/${desktop}"      "${working_dir}/launcher.desktop" &> /dev/null

[ -d "${working_dir}/squashfs-root/usr/share/mime" ] && {
  mv "${working_dir}/squashfs-root/usr/share/mime" "${working_dir}" &> /dev/null
}

rm -rf "${working_dir}/squashfs-root/" &> /dev/null

echo "${offset}" > "${working_dir}/OFFSET"

version=$(cat "${working_dir}/launcher.desktop" | grep ^"X-AppImage-Version=" | cut -d= -f2 | head -n1)

[ -z "${version}" ] && {
  version=$(md5sum "${appimage}" | cut -c -6)
  version="0.${version}"
}

echo "${version}" > "${working_dir}/VERSION"

echo -n "Directory with data: " > /dev/stderr
echo "${working_dir}"
