name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{TELEGRAM.TG_TOKEN}}
      TELEGRAM_ID:    ${{TELEGRAM.TG_GROUP_ID}}
    steps:
      - uses: actions/checkout@v2
      - name: Constroi o pacote
        run: bash build.sh

